version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: ${PORT}
    ports:
      - "${PORT}:${PORT}"
    container_name: api-container
    env_file:
      - .env
