// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package controller

import (
	"context"
	"ing-soft-2-tp1/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// BlockUser provides a mock function for the type MockUserService
func (_mock *MockUserService) BlockUser(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for BlockUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserService_BlockUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlockUser'
type MockUserService_BlockUser_Call struct {
	*mock.Call
}

// BlockUser is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *MockUserService_Expecter) BlockUser(ctx interface{}, id interface{}) *MockUserService_BlockUser_Call {
	return &MockUserService_BlockUser_Call{Call: _e.mock.On("BlockUser", ctx, id)}
}

func (_c *MockUserService_BlockUser_Call) Run(run func(ctx context.Context, id int)) *MockUserService_BlockUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockUserService_BlockUser_Call) Return(err error) *MockUserService_BlockUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserService_BlockUser_Call) RunAndReturn(run func(ctx context.Context, id int) error) *MockUserService_BlockUser_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function for the type MockUserService
func (_mock *MockUserService) CreateUser(ctx context.Context, request models.CreateUserRequest, admin bool) (*models.User, error) {
	ret := _mock.Called(ctx, request, admin)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.CreateUserRequest, bool) (*models.User, error)); ok {
		return returnFunc(ctx, request, admin)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.CreateUserRequest, bool) *models.User); ok {
		r0 = returnFunc(ctx, request, admin)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.CreateUserRequest, bool) error); ok {
		r1 = returnFunc(ctx, request, admin)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUserService_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx
//   - request
//   - admin
func (_e *MockUserService_Expecter) CreateUser(ctx interface{}, request interface{}, admin interface{}) *MockUserService_CreateUser_Call {
	return &MockUserService_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, request, admin)}
}

func (_c *MockUserService_CreateUser_Call) Run(run func(ctx context.Context, request models.CreateUserRequest, admin bool)) *MockUserService_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.CreateUserRequest), args[2].(bool))
	})
	return _c
}

func (_c *MockUserService_CreateUser_Call) Return(user *models.User, err error) *MockUserService_CreateUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserService_CreateUser_Call) RunAndReturn(run func(ctx context.Context, request models.CreateUserRequest, admin bool) (*models.User, error)) *MockUserService_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function for the type MockUserService
func (_mock *MockUserService) DeleteUser(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserService_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockUserService_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *MockUserService_Expecter) DeleteUser(ctx interface{}, id interface{}) *MockUserService_DeleteUser_Call {
	return &MockUserService_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, id)}
}

func (_c *MockUserService_DeleteUser_Call) Run(run func(ctx context.Context, id int)) *MockUserService_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockUserService_DeleteUser_Call) Return(err error) *MockUserService_DeleteUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserService_DeleteUser_Call) RunAndReturn(run func(ctx context.Context, id int) error) *MockUserService_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllUsers provides a mock function for the type MockUserService
func (_mock *MockUserService) GetAllUsers(ctx context.Context) ([]models.User, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllUsers")
	}

	var r0 []models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]models.User, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []models.User); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_GetAllUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllUsers'
type MockUserService_GetAllUsers_Call struct {
	*mock.Call
}

// GetAllUsers is a helper method to define mock.On call
//   - ctx
func (_e *MockUserService_Expecter) GetAllUsers(ctx interface{}) *MockUserService_GetAllUsers_Call {
	return &MockUserService_GetAllUsers_Call{Call: _e.mock.On("GetAllUsers", ctx)}
}

func (_c *MockUserService_GetAllUsers_Call) Run(run func(ctx context.Context)) *MockUserService_GetAllUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockUserService_GetAllUsers_Call) Return(users []models.User, err error) *MockUserService_GetAllUsers_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockUserService_GetAllUsers_Call) RunAndReturn(run func(ctx context.Context) ([]models.User, error)) *MockUserService_GetAllUsers_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmail provides a mock function for the type MockUserService
func (_mock *MockUserService) GetUserByEmail(ctx context.Context, email string) (*models.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type MockUserService_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - ctx
//   - email
func (_e *MockUserService_Expecter) GetUserByEmail(ctx interface{}, email interface{}) *MockUserService_GetUserByEmail_Call {
	return &MockUserService_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", ctx, email)}
}

func (_c *MockUserService_GetUserByEmail_Call) Run(run func(ctx context.Context, email string)) *MockUserService_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserService_GetUserByEmail_Call) Return(user *models.User, err error) *MockUserService_GetUserByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserService_GetUserByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*models.User, error)) *MockUserService_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserById provides a mock function for the type MockUserService
func (_mock *MockUserService) GetUserById(ctx context.Context, id int) (*models.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserById")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*models.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *models.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_GetUserById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserById'
type MockUserService_GetUserById_Call struct {
	*mock.Call
}

// GetUserById is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *MockUserService_Expecter) GetUserById(ctx interface{}, id interface{}) *MockUserService_GetUserById_Call {
	return &MockUserService_GetUserById_Call{Call: _e.mock.On("GetUserById", ctx, id)}
}

func (_c *MockUserService_GetUserById_Call) Run(run func(ctx context.Context, id int)) *MockUserService_GetUserById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockUserService_GetUserById_Call) Return(user *models.User, err error) *MockUserService_GetUserById_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserService_GetUserById_Call) RunAndReturn(run func(ctx context.Context, id int) (*models.User, error)) *MockUserService_GetUserById_Call {
	_c.Call.Return(run)
	return _c
}

// ModifyLocation provides a mock function for the type MockUserService
func (_mock *MockUserService) ModifyLocation(ctx context.Context, id int, newLocation string) error {
	ret := _mock.Called(ctx, id, newLocation)

	if len(ret) == 0 {
		panic("no return value specified for ModifyLocation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) error); ok {
		r0 = returnFunc(ctx, id, newLocation)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserService_ModifyLocation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ModifyLocation'
type MockUserService_ModifyLocation_Call struct {
	*mock.Call
}

// ModifyLocation is a helper method to define mock.On call
//   - ctx
//   - id
//   - newLocation
func (_e *MockUserService_Expecter) ModifyLocation(ctx interface{}, id interface{}, newLocation interface{}) *MockUserService_ModifyLocation_Call {
	return &MockUserService_ModifyLocation_Call{Call: _e.mock.On("ModifyLocation", ctx, id, newLocation)}
}

func (_c *MockUserService_ModifyLocation_Call) Run(run func(ctx context.Context, id int, newLocation string)) *MockUserService_ModifyLocation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(string))
	})
	return _c
}

func (_c *MockUserService_ModifyLocation_Call) Return(err error) *MockUserService_ModifyLocation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserService_ModifyLocation_Call) RunAndReturn(run func(ctx context.Context, id int, newLocation string) error) *MockUserService_ModifyLocation_Call {
	_c.Call.Return(run)
	return _c
}

// ModifyUser provides a mock function for the type MockUserService
func (_mock *MockUserService) ModifyUser(ctx context.Context, user *models.User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for ModifyUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserService_ModifyUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ModifyUser'
type MockUserService_ModifyUser_Call struct {
	*mock.Call
}

// ModifyUser is a helper method to define mock.On call
//   - ctx
//   - user
func (_e *MockUserService_Expecter) ModifyUser(ctx interface{}, user interface{}) *MockUserService_ModifyUser_Call {
	return &MockUserService_ModifyUser_Call{Call: _e.mock.On("ModifyUser", ctx, user)}
}

func (_c *MockUserService_ModifyUser_Call) Run(run func(ctx context.Context, user *models.User)) *MockUserService_ModifyUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.User))
	})
	return _c
}

func (_c *MockUserService_ModifyUser_Call) Return(err error) *MockUserService_ModifyUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserService_ModifyUser_Call) RunAndReturn(run func(ctx context.Context, user *models.User) error) *MockUserService_ModifyUser_Call {
	_c.Call.Return(run)
	return _c
}
