// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repositories

import (
	"context"
	"time"

	"github.com/Ingenieria-de-Software-2-Gupo-14/user-api/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBlockedUserRepository creates a new instance of MockBlockedUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBlockedUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBlockedUserRepository {
	mock := &MockBlockedUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBlockedUserRepository is an autogenerated mock type for the BlockedUserRepository type
type MockBlockedUserRepository struct {
	mock.Mock
}

type MockBlockedUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBlockedUserRepository) EXPECT() *MockBlockedUserRepository_Expecter {
	return &MockBlockedUserRepository_Expecter{mock: &_m.Mock}
}

// BlockUser provides a mock function for the type MockBlockedUserRepository
func (_mock *MockBlockedUserRepository) BlockUser(ctx context.Context, blockedUserID int, reason string, blockerID *int, blockedUntil *time.Time) error {
	ret := _mock.Called(ctx, blockedUserID, reason, blockerID, blockedUntil)

	if len(ret) == 0 {
		panic("no return value specified for BlockUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string, *int, *time.Time) error); ok {
		r0 = returnFunc(ctx, blockedUserID, reason, blockerID, blockedUntil)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBlockedUserRepository_BlockUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlockUser'
type MockBlockedUserRepository_BlockUser_Call struct {
	*mock.Call
}

// BlockUser is a helper method to define mock.On call
//   - ctx
//   - blockedUserID
//   - reason
//   - blockerID
//   - blockedUntil
func (_e *MockBlockedUserRepository_Expecter) BlockUser(ctx interface{}, blockedUserID interface{}, reason interface{}, blockerID interface{}, blockedUntil interface{}) *MockBlockedUserRepository_BlockUser_Call {
	return &MockBlockedUserRepository_BlockUser_Call{Call: _e.mock.On("BlockUser", ctx, blockedUserID, reason, blockerID, blockedUntil)}
}

func (_c *MockBlockedUserRepository_BlockUser_Call) Run(run func(ctx context.Context, blockedUserID int, reason string, blockerID *int, blockedUntil *time.Time)) *MockBlockedUserRepository_BlockUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(string), args[3].(*int), args[4].(*time.Time))
	})
	return _c
}

func (_c *MockBlockedUserRepository_BlockUser_Call) Return(err error) *MockBlockedUserRepository_BlockUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBlockedUserRepository_BlockUser_Call) RunAndReturn(run func(ctx context.Context, blockedUserID int, reason string, blockerID *int, blockedUntil *time.Time) error) *MockBlockedUserRepository_BlockUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetBlocksByUserId provides a mock function for the type MockBlockedUserRepository
func (_mock *MockBlockedUserRepository) GetBlocksByUserId(ctx context.Context, userID int) ([]models.BlockedUser, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetBlocksByUserId")
	}

	var r0 []models.BlockedUser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]models.BlockedUser, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []models.BlockedUser); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.BlockedUser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBlockedUserRepository_GetBlocksByUserId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlocksByUserId'
type MockBlockedUserRepository_GetBlocksByUserId_Call struct {
	*mock.Call
}

// GetBlocksByUserId is a helper method to define mock.On call
//   - ctx
//   - userID
func (_e *MockBlockedUserRepository_Expecter) GetBlocksByUserId(ctx interface{}, userID interface{}) *MockBlockedUserRepository_GetBlocksByUserId_Call {
	return &MockBlockedUserRepository_GetBlocksByUserId_Call{Call: _e.mock.On("GetBlocksByUserId", ctx, userID)}
}

func (_c *MockBlockedUserRepository_GetBlocksByUserId_Call) Run(run func(ctx context.Context, userID int)) *MockBlockedUserRepository_GetBlocksByUserId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockBlockedUserRepository_GetBlocksByUserId_Call) Return(blockedUsers []models.BlockedUser, err error) *MockBlockedUserRepository_GetBlocksByUserId_Call {
	_c.Call.Return(blockedUsers, err)
	return _c
}

func (_c *MockBlockedUserRepository_GetBlocksByUserId_Call) RunAndReturn(run func(ctx context.Context, userID int) ([]models.BlockedUser, error)) *MockBlockedUserRepository_GetBlocksByUserId_Call {
	_c.Call.Return(run)
	return _c
}

// UnblockUser provides a mock function for the type MockBlockedUserRepository
func (_mock *MockBlockedUserRepository) UnblockUser(ctx context.Context, blockedUserID int) error {
	ret := _mock.Called(ctx, blockedUserID)

	if len(ret) == 0 {
		panic("no return value specified for UnblockUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, blockedUserID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBlockedUserRepository_UnblockUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnblockUser'
type MockBlockedUserRepository_UnblockUser_Call struct {
	*mock.Call
}

// UnblockUser is a helper method to define mock.On call
//   - ctx
//   - blockedUserID
func (_e *MockBlockedUserRepository_Expecter) UnblockUser(ctx interface{}, blockedUserID interface{}) *MockBlockedUserRepository_UnblockUser_Call {
	return &MockBlockedUserRepository_UnblockUser_Call{Call: _e.mock.On("UnblockUser", ctx, blockedUserID)}
}

func (_c *MockBlockedUserRepository_UnblockUser_Call) Run(run func(ctx context.Context, blockedUserID int)) *MockBlockedUserRepository_UnblockUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockBlockedUserRepository_UnblockUser_Call) Return(err error) *MockBlockedUserRepository_UnblockUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBlockedUserRepository_UnblockUser_Call) RunAndReturn(run func(ctx context.Context, blockedUserID int) error) *MockBlockedUserRepository_UnblockUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChatRepository creates a new instance of MockChatRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatRepository {
	mock := &MockChatRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChatRepository is an autogenerated mock type for the ChatRepository type
type MockChatRepository struct {
	mock.Mock
}

type MockChatRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatRepository) EXPECT() *MockChatRepository_Expecter {
	return &MockChatRepository_Expecter{mock: &_m.Mock}
}

// GetLatestMessage provides a mock function for the type MockChatRepository
func (_mock *MockChatRepository) GetLatestMessage(context1 context.Context, userId int) (*models.ChatMessage, error) {
	ret := _mock.Called(context1, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestMessage")
	}

	var r0 *models.ChatMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*models.ChatMessage, error)); ok {
		return returnFunc(context1, userId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *models.ChatMessage); ok {
		r0 = returnFunc(context1, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ChatMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(context1, userId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatRepository_GetLatestMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestMessage'
type MockChatRepository_GetLatestMessage_Call struct {
	*mock.Call
}

// GetLatestMessage is a helper method to define mock.On call
//   - context1
//   - userId
func (_e *MockChatRepository_Expecter) GetLatestMessage(context1 interface{}, userId interface{}) *MockChatRepository_GetLatestMessage_Call {
	return &MockChatRepository_GetLatestMessage_Call{Call: _e.mock.On("GetLatestMessage", context1, userId)}
}

func (_c *MockChatRepository_GetLatestMessage_Call) Run(run func(context1 context.Context, userId int)) *MockChatRepository_GetLatestMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockChatRepository_GetLatestMessage_Call) Return(chatMessage *models.ChatMessage, err error) *MockChatRepository_GetLatestMessage_Call {
	_c.Call.Return(chatMessage, err)
	return _c
}

func (_c *MockChatRepository_GetLatestMessage_Call) RunAndReturn(run func(context1 context.Context, userId int) (*models.ChatMessage, error)) *MockChatRepository_GetLatestMessage_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessages provides a mock function for the type MockChatRepository
func (_mock *MockChatRepository) GetMessages(ctx context.Context, id int, date string) ([]models.ChatMessage, error) {
	ret := _mock.Called(ctx, id, date)

	if len(ret) == 0 {
		panic("no return value specified for GetMessages")
	}

	var r0 []models.ChatMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) ([]models.ChatMessage, error)); ok {
		return returnFunc(ctx, id, date)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) []models.ChatMessage); ok {
		r0 = returnFunc(ctx, id, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.ChatMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, string) error); ok {
		r1 = returnFunc(ctx, id, date)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatRepository_GetMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessages'
type MockChatRepository_GetMessages_Call struct {
	*mock.Call
}

// GetMessages is a helper method to define mock.On call
//   - ctx
//   - id
//   - date
func (_e *MockChatRepository_Expecter) GetMessages(ctx interface{}, id interface{}, date interface{}) *MockChatRepository_GetMessages_Call {
	return &MockChatRepository_GetMessages_Call{Call: _e.mock.On("GetMessages", ctx, id, date)}
}

func (_c *MockChatRepository_GetMessages_Call) Run(run func(ctx context.Context, id int, date string)) *MockChatRepository_GetMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(string))
	})
	return _c
}

func (_c *MockChatRepository_GetMessages_Call) Return(chatMessages []models.ChatMessage, err error) *MockChatRepository_GetMessages_Call {
	_c.Call.Return(chatMessages, err)
	return _c
}

func (_c *MockChatRepository_GetMessages_Call) RunAndReturn(run func(ctx context.Context, id int, date string) ([]models.ChatMessage, error)) *MockChatRepository_GetMessages_Call {
	_c.Call.Return(run)
	return _c
}

// NewMessage provides a mock function for the type MockChatRepository
func (_mock *MockChatRepository) NewMessage(ctx context.Context, id int, message string, sender string) error {
	ret := _mock.Called(ctx, id, message, sender)

	if len(ret) == 0 {
		panic("no return value specified for NewMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string, string) error); ok {
		r0 = returnFunc(ctx, id, message, sender)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatRepository_NewMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewMessage'
type MockChatRepository_NewMessage_Call struct {
	*mock.Call
}

// NewMessage is a helper method to define mock.On call
//   - ctx
//   - id
//   - message
//   - sender
func (_e *MockChatRepository_Expecter) NewMessage(ctx interface{}, id interface{}, message interface{}, sender interface{}) *MockChatRepository_NewMessage_Call {
	return &MockChatRepository_NewMessage_Call{Call: _e.mock.On("NewMessage", ctx, id, message, sender)}
}

func (_c *MockChatRepository_NewMessage_Call) Run(run func(ctx context.Context, id int, message string, sender string)) *MockChatRepository_NewMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockChatRepository_NewMessage_Call) Return(err error) *MockChatRepository_NewMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatRepository_NewMessage_Call) RunAndReturn(run func(ctx context.Context, id int, message string, sender string) error) *MockChatRepository_NewMessage_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMessageFeedback provides a mock function for the type MockChatRepository
func (_mock *MockChatRepository) UpdateMessageFeedback(context1 context.Context, userId int, messageId int, feedback string) error {
	ret := _mock.Called(context1, userId, messageId, feedback)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMessageFeedback")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, string) error); ok {
		r0 = returnFunc(context1, userId, messageId, feedback)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatRepository_UpdateMessageFeedback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMessageFeedback'
type MockChatRepository_UpdateMessageFeedback_Call struct {
	*mock.Call
}

// UpdateMessageFeedback is a helper method to define mock.On call
//   - context1
//   - userId
//   - messageId
//   - feedback
func (_e *MockChatRepository_Expecter) UpdateMessageFeedback(context1 interface{}, userId interface{}, messageId interface{}, feedback interface{}) *MockChatRepository_UpdateMessageFeedback_Call {
	return &MockChatRepository_UpdateMessageFeedback_Call{Call: _e.mock.On("UpdateMessageFeedback", context1, userId, messageId, feedback)}
}

func (_c *MockChatRepository_UpdateMessageFeedback_Call) Run(run func(context1 context.Context, userId int, messageId int, feedback string)) *MockChatRepository_UpdateMessageFeedback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(string))
	})
	return _c
}

func (_c *MockChatRepository_UpdateMessageFeedback_Call) Return(err error) *MockChatRepository_UpdateMessageFeedback_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatRepository_UpdateMessageFeedback_Call) RunAndReturn(run func(context1 context.Context, userId int, messageId int, feedback string) error) *MockChatRepository_UpdateMessageFeedback_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMessageRating provides a mock function for the type MockChatRepository
func (_mock *MockChatRepository) UpdateMessageRating(context1 context.Context, userId int, messageId int, rating int) error {
	ret := _mock.Called(context1, userId, messageId, rating)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMessageRating")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, int) error); ok {
		r0 = returnFunc(context1, userId, messageId, rating)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatRepository_UpdateMessageRating_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMessageRating'
type MockChatRepository_UpdateMessageRating_Call struct {
	*mock.Call
}

// UpdateMessageRating is a helper method to define mock.On call
//   - context1
//   - userId
//   - messageId
//   - rating
func (_e *MockChatRepository_Expecter) UpdateMessageRating(context1 interface{}, userId interface{}, messageId interface{}, rating interface{}) *MockChatRepository_UpdateMessageRating_Call {
	return &MockChatRepository_UpdateMessageRating_Call{Call: _e.mock.On("UpdateMessageRating", context1, userId, messageId, rating)}
}

func (_c *MockChatRepository_UpdateMessageRating_Call) Run(run func(context1 context.Context, userId int, messageId int, rating int)) *MockChatRepository_UpdateMessageRating_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockChatRepository_UpdateMessageRating_Call) Return(err error) *MockChatRepository_UpdateMessageRating_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatRepository_UpdateMessageRating_Call) RunAndReturn(run func(context1 context.Context, userId int, messageId int, rating int) error) *MockChatRepository_UpdateMessageRating_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLoginAttemptRepository creates a new instance of MockLoginAttemptRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoginAttemptRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoginAttemptRepository {
	mock := &MockLoginAttemptRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLoginAttemptRepository is an autogenerated mock type for the LoginAttemptRepository type
type MockLoginAttemptRepository struct {
	mock.Mock
}

type MockLoginAttemptRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoginAttemptRepository) EXPECT() *MockLoginAttemptRepository_Expecter {
	return &MockLoginAttemptRepository_Expecter{mock: &_m.Mock}
}

// AddLoginAttempt provides a mock function for the type MockLoginAttemptRepository
func (_mock *MockLoginAttemptRepository) AddLoginAttempt(ctx context.Context, userID int, ipAddress string, userAgent string, successful bool) error {
	ret := _mock.Called(ctx, userID, ipAddress, userAgent, successful)

	if len(ret) == 0 {
		panic("no return value specified for AddLoginAttempt")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string, string, bool) error); ok {
		r0 = returnFunc(ctx, userID, ipAddress, userAgent, successful)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLoginAttemptRepository_AddLoginAttempt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddLoginAttempt'
type MockLoginAttemptRepository_AddLoginAttempt_Call struct {
	*mock.Call
}

// AddLoginAttempt is a helper method to define mock.On call
//   - ctx
//   - userID
//   - ipAddress
//   - userAgent
//   - successful
func (_e *MockLoginAttemptRepository_Expecter) AddLoginAttempt(ctx interface{}, userID interface{}, ipAddress interface{}, userAgent interface{}, successful interface{}) *MockLoginAttemptRepository_AddLoginAttempt_Call {
	return &MockLoginAttemptRepository_AddLoginAttempt_Call{Call: _e.mock.On("AddLoginAttempt", ctx, userID, ipAddress, userAgent, successful)}
}

func (_c *MockLoginAttemptRepository_AddLoginAttempt_Call) Run(run func(ctx context.Context, userID int, ipAddress string, userAgent string, successful bool)) *MockLoginAttemptRepository_AddLoginAttempt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(string), args[3].(string), args[4].(bool))
	})
	return _c
}

func (_c *MockLoginAttemptRepository_AddLoginAttempt_Call) Return(err error) *MockLoginAttemptRepository_AddLoginAttempt_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLoginAttemptRepository_AddLoginAttempt_Call) RunAndReturn(run func(ctx context.Context, userID int, ipAddress string, userAgent string, successful bool) error) *MockLoginAttemptRepository_AddLoginAttempt_Call {
	_c.Call.Return(run)
	return _c
}

// BadLoginAttemptsInLast10Minutes provides a mock function for the type MockLoginAttemptRepository
func (_mock *MockLoginAttemptRepository) BadLoginAttemptsInLast10Minutes(ctx context.Context, userID int) (int, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for BadLoginAttemptsInLast10Minutes")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (int, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLoginAttemptRepository_BadLoginAttemptsInLast10Minutes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BadLoginAttemptsInLast10Minutes'
type MockLoginAttemptRepository_BadLoginAttemptsInLast10Minutes_Call struct {
	*mock.Call
}

// BadLoginAttemptsInLast10Minutes is a helper method to define mock.On call
//   - ctx
//   - userID
func (_e *MockLoginAttemptRepository_Expecter) BadLoginAttemptsInLast10Minutes(ctx interface{}, userID interface{}) *MockLoginAttemptRepository_BadLoginAttemptsInLast10Minutes_Call {
	return &MockLoginAttemptRepository_BadLoginAttemptsInLast10Minutes_Call{Call: _e.mock.On("BadLoginAttemptsInLast10Minutes", ctx, userID)}
}

func (_c *MockLoginAttemptRepository_BadLoginAttemptsInLast10Minutes_Call) Run(run func(ctx context.Context, userID int)) *MockLoginAttemptRepository_BadLoginAttemptsInLast10Minutes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockLoginAttemptRepository_BadLoginAttemptsInLast10Minutes_Call) Return(n int, err error) *MockLoginAttemptRepository_BadLoginAttemptsInLast10Minutes_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockLoginAttemptRepository_BadLoginAttemptsInLast10Minutes_Call) RunAndReturn(run func(ctx context.Context, userID int) (int, error)) *MockLoginAttemptRepository_BadLoginAttemptsInLast10Minutes_Call {
	_c.Call.Return(run)
	return _c
}

// GetLoginsByUserId provides a mock function for the type MockLoginAttemptRepository
func (_mock *MockLoginAttemptRepository) GetLoginsByUserId(ctx context.Context, userID int, limit int, offset int) ([]*models.LoginAttempt, error) {
	ret := _mock.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetLoginsByUserId")
	}

	var r0 []*models.LoginAttempt
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, int) ([]*models.LoginAttempt, error)); ok {
		return returnFunc(ctx, userID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, int) []*models.LoginAttempt); ok {
		r0 = returnFunc(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.LoginAttempt)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int, int) error); ok {
		r1 = returnFunc(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLoginAttemptRepository_GetLoginsByUserId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLoginsByUserId'
type MockLoginAttemptRepository_GetLoginsByUserId_Call struct {
	*mock.Call
}

// GetLoginsByUserId is a helper method to define mock.On call
//   - ctx
//   - userID
//   - limit
//   - offset
func (_e *MockLoginAttemptRepository_Expecter) GetLoginsByUserId(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *MockLoginAttemptRepository_GetLoginsByUserId_Call {
	return &MockLoginAttemptRepository_GetLoginsByUserId_Call{Call: _e.mock.On("GetLoginsByUserId", ctx, userID, limit, offset)}
}

func (_c *MockLoginAttemptRepository_GetLoginsByUserId_Call) Run(run func(ctx context.Context, userID int, limit int, offset int)) *MockLoginAttemptRepository_GetLoginsByUserId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockLoginAttemptRepository_GetLoginsByUserId_Call) Return(loginAttempts []*models.LoginAttempt, err error) *MockLoginAttemptRepository_GetLoginsByUserId_Call {
	_c.Call.Return(loginAttempts, err)
	return _c
}

func (_c *MockLoginAttemptRepository_GetLoginsByUserId_Call) RunAndReturn(run func(ctx context.Context, userID int, limit int, offset int) ([]*models.LoginAttempt, error)) *MockLoginAttemptRepository_GetLoginsByUserId_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRulesRepository creates a new instance of MockRulesRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRulesRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRulesRepository {
	mock := &MockRulesRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRulesRepository is an autogenerated mock type for the RulesRepository type
type MockRulesRepository struct {
	mock.Mock
}

type MockRulesRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRulesRepository) EXPECT() *MockRulesRepository_Expecter {
	return &MockRulesRepository_Expecter{mock: &_m.Mock}
}

// AddRule provides a mock function for the type MockRulesRepository
func (_mock *MockRulesRepository) AddRule(ctx context.Context, rule models.Rule, userId int) error {
	ret := _mock.Called(ctx, rule, userId)

	if len(ret) == 0 {
		panic("no return value specified for AddRule")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Rule, int) error); ok {
		r0 = returnFunc(ctx, rule, userId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRulesRepository_AddRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddRule'
type MockRulesRepository_AddRule_Call struct {
	*mock.Call
}

// AddRule is a helper method to define mock.On call
//   - ctx
//   - rule
//   - userId
func (_e *MockRulesRepository_Expecter) AddRule(ctx interface{}, rule interface{}, userId interface{}) *MockRulesRepository_AddRule_Call {
	return &MockRulesRepository_AddRule_Call{Call: _e.mock.On("AddRule", ctx, rule, userId)}
}

func (_c *MockRulesRepository_AddRule_Call) Run(run func(ctx context.Context, rule models.Rule, userId int)) *MockRulesRepository_AddRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.Rule), args[2].(int))
	})
	return _c
}

func (_c *MockRulesRepository_AddRule_Call) Return(err error) *MockRulesRepository_AddRule_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRulesRepository_AddRule_Call) RunAndReturn(run func(ctx context.Context, rule models.Rule, userId int) error) *MockRulesRepository_AddRule_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRule provides a mock function for the type MockRulesRepository
func (_mock *MockRulesRepository) DeleteRule(ctx context.Context, ruleId int, userId int) error {
	ret := _mock.Called(ctx, ruleId, userId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRule")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = returnFunc(ctx, ruleId, userId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRulesRepository_DeleteRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRule'
type MockRulesRepository_DeleteRule_Call struct {
	*mock.Call
}

// DeleteRule is a helper method to define mock.On call
//   - ctx
//   - ruleId
//   - userId
func (_e *MockRulesRepository_Expecter) DeleteRule(ctx interface{}, ruleId interface{}, userId interface{}) *MockRulesRepository_DeleteRule_Call {
	return &MockRulesRepository_DeleteRule_Call{Call: _e.mock.On("DeleteRule", ctx, ruleId, userId)}
}

func (_c *MockRulesRepository_DeleteRule_Call) Run(run func(ctx context.Context, ruleId int, userId int)) *MockRulesRepository_DeleteRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockRulesRepository_DeleteRule_Call) Return(err error) *MockRulesRepository_DeleteRule_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRulesRepository_DeleteRule_Call) RunAndReturn(run func(ctx context.Context, ruleId int, userId int) error) *MockRulesRepository_DeleteRule_Call {
	_c.Call.Return(run)
	return _c
}

// GetAudit provides a mock function for the type MockRulesRepository
func (_mock *MockRulesRepository) GetAudit(ctx context.Context) ([]models.Audit, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAudit")
	}

	var r0 []models.Audit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]models.Audit, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []models.Audit); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Audit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRulesRepository_GetAudit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAudit'
type MockRulesRepository_GetAudit_Call struct {
	*mock.Call
}

// GetAudit is a helper method to define mock.On call
//   - ctx
func (_e *MockRulesRepository_Expecter) GetAudit(ctx interface{}) *MockRulesRepository_GetAudit_Call {
	return &MockRulesRepository_GetAudit_Call{Call: _e.mock.On("GetAudit", ctx)}
}

func (_c *MockRulesRepository_GetAudit_Call) Run(run func(ctx context.Context)) *MockRulesRepository_GetAudit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRulesRepository_GetAudit_Call) Return(audits []models.Audit, err error) *MockRulesRepository_GetAudit_Call {
	_c.Call.Return(audits, err)
	return _c
}

func (_c *MockRulesRepository_GetAudit_Call) RunAndReturn(run func(ctx context.Context) ([]models.Audit, error)) *MockRulesRepository_GetAudit_Call {
	_c.Call.Return(run)
	return _c
}

// GetRules provides a mock function for the type MockRulesRepository
func (_mock *MockRulesRepository) GetRules(ctx context.Context) ([]models.Rule, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRules")
	}

	var r0 []models.Rule
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]models.Rule, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []models.Rule); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Rule)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRulesRepository_GetRules_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRules'
type MockRulesRepository_GetRules_Call struct {
	*mock.Call
}

// GetRules is a helper method to define mock.On call
//   - ctx
func (_e *MockRulesRepository_Expecter) GetRules(ctx interface{}) *MockRulesRepository_GetRules_Call {
	return &MockRulesRepository_GetRules_Call{Call: _e.mock.On("GetRules", ctx)}
}

func (_c *MockRulesRepository_GetRules_Call) Run(run func(ctx context.Context)) *MockRulesRepository_GetRules_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRulesRepository_GetRules_Call) Return(rules []models.Rule, err error) *MockRulesRepository_GetRules_Call {
	_c.Call.Return(rules, err)
	return _c
}

func (_c *MockRulesRepository_GetRules_Call) RunAndReturn(run func(ctx context.Context) ([]models.Rule, error)) *MockRulesRepository_GetRules_Call {
	_c.Call.Return(run)
	return _c
}

// ModifyRule provides a mock function for the type MockRulesRepository
func (_mock *MockRulesRepository) ModifyRule(ctx context.Context, ruleId int, modification models.RuleModify, userId int) error {
	ret := _mock.Called(ctx, ruleId, modification, userId)

	if len(ret) == 0 {
		panic("no return value specified for ModifyRule")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, models.RuleModify, int) error); ok {
		r0 = returnFunc(ctx, ruleId, modification, userId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRulesRepository_ModifyRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ModifyRule'
type MockRulesRepository_ModifyRule_Call struct {
	*mock.Call
}

// ModifyRule is a helper method to define mock.On call
//   - ctx
//   - ruleId
//   - modification
//   - userId
func (_e *MockRulesRepository_Expecter) ModifyRule(ctx interface{}, ruleId interface{}, modification interface{}, userId interface{}) *MockRulesRepository_ModifyRule_Call {
	return &MockRulesRepository_ModifyRule_Call{Call: _e.mock.On("ModifyRule", ctx, ruleId, modification, userId)}
}

func (_c *MockRulesRepository_ModifyRule_Call) Run(run func(ctx context.Context, ruleId int, modification models.RuleModify, userId int)) *MockRulesRepository_ModifyRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(models.RuleModify), args[3].(int))
	})
	return _c
}

func (_c *MockRulesRepository_ModifyRule_Call) Return(err error) *MockRulesRepository_ModifyRule_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRulesRepository_ModifyRule_Call) RunAndReturn(run func(ctx context.Context, ruleId int, modification models.RuleModify, userId int) error) *MockRulesRepository_ModifyRule_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// AddNotificationToken provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) AddNotificationToken(ctx context.Context, id int, text string) error {
	ret := _mock.Called(ctx, id, text)

	if len(ret) == 0 {
		panic("no return value specified for AddNotificationToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) error); ok {
		r0 = returnFunc(ctx, id, text)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_AddNotificationToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddNotificationToken'
type MockUserRepository_AddNotificationToken_Call struct {
	*mock.Call
}

// AddNotificationToken is a helper method to define mock.On call
//   - ctx
//   - id
//   - text
func (_e *MockUserRepository_Expecter) AddNotificationToken(ctx interface{}, id interface{}, text interface{}) *MockUserRepository_AddNotificationToken_Call {
	return &MockUserRepository_AddNotificationToken_Call{Call: _e.mock.On("AddNotificationToken", ctx, id, text)}
}

func (_c *MockUserRepository_AddNotificationToken_Call) Run(run func(ctx context.Context, id int, text string)) *MockUserRepository_AddNotificationToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(string))
	})
	return _c
}

func (_c *MockUserRepository_AddNotificationToken_Call) Return(err error) *MockUserRepository_AddNotificationToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_AddNotificationToken_Call) RunAndReturn(run func(ctx context.Context, id int, text string) error) *MockUserRepository_AddNotificationToken_Call {
	_c.Call.Return(run)
	return _c
}

// AddPasswordResetToken provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) AddPasswordResetToken(ctx context.Context, id int, email string, token string, tokenExpiration time.Time) error {
	ret := _mock.Called(ctx, id, email, token, tokenExpiration)

	if len(ret) == 0 {
		panic("no return value specified for AddPasswordResetToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string, string, time.Time) error); ok {
		r0 = returnFunc(ctx, id, email, token, tokenExpiration)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_AddPasswordResetToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPasswordResetToken'
type MockUserRepository_AddPasswordResetToken_Call struct {
	*mock.Call
}

// AddPasswordResetToken is a helper method to define mock.On call
//   - ctx
//   - id
//   - email
//   - token
//   - tokenExpiration
func (_e *MockUserRepository_Expecter) AddPasswordResetToken(ctx interface{}, id interface{}, email interface{}, token interface{}, tokenExpiration interface{}) *MockUserRepository_AddPasswordResetToken_Call {
	return &MockUserRepository_AddPasswordResetToken_Call{Call: _e.mock.On("AddPasswordResetToken", ctx, id, email, token, tokenExpiration)}
}

func (_c *MockUserRepository_AddPasswordResetToken_Call) Run(run func(ctx context.Context, id int, email string, token string, tokenExpiration time.Time)) *MockUserRepository_AddPasswordResetToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(string), args[3].(string), args[4].(time.Time))
	})
	return _c
}

func (_c *MockUserRepository_AddPasswordResetToken_Call) Return(err error) *MockUserRepository_AddPasswordResetToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_AddPasswordResetToken_Call) RunAndReturn(run func(ctx context.Context, id int, email string, token string, tokenExpiration time.Time) error) *MockUserRepository_AddPasswordResetToken_Call {
	_c.Call.Return(run)
	return _c
}

// AddUser provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) AddUser(ctx context.Context, user *models.User) (int, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for AddUser")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.User) (int, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.User) int); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_AddUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUser'
type MockUserRepository_AddUser_Call struct {
	*mock.Call
}

// AddUser is a helper method to define mock.On call
//   - ctx
//   - user
func (_e *MockUserRepository_Expecter) AddUser(ctx interface{}, user interface{}) *MockUserRepository_AddUser_Call {
	return &MockUserRepository_AddUser_Call{Call: _e.mock.On("AddUser", ctx, user)}
}

func (_c *MockUserRepository_AddUser_Call) Run(run func(ctx context.Context, user *models.User)) *MockUserRepository_AddUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.User))
	})
	return _c
}

func (_c *MockUserRepository_AddUser_Call) Return(n int, err error) *MockUserRepository_AddUser_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockUserRepository_AddUser_Call) RunAndReturn(run func(ctx context.Context, user *models.User) (int, error)) *MockUserRepository_AddUser_Call {
	_c.Call.Return(run)
	return _c
}

// CheckPreference provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) CheckPreference(ctx context.Context, id int, notificationType string) (bool, error) {
	ret := _mock.Called(ctx, id, notificationType)

	if len(ret) == 0 {
		panic("no return value specified for CheckPreference")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) (bool, error)); ok {
		return returnFunc(ctx, id, notificationType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) bool); ok {
		r0 = returnFunc(ctx, id, notificationType)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, string) error); ok {
		r1 = returnFunc(ctx, id, notificationType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_CheckPreference_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckPreference'
type MockUserRepository_CheckPreference_Call struct {
	*mock.Call
}

// CheckPreference is a helper method to define mock.On call
//   - ctx
//   - id
//   - notificationType
func (_e *MockUserRepository_Expecter) CheckPreference(ctx interface{}, id interface{}, notificationType interface{}) *MockUserRepository_CheckPreference_Call {
	return &MockUserRepository_CheckPreference_Call{Call: _e.mock.On("CheckPreference", ctx, id, notificationType)}
}

func (_c *MockUserRepository_CheckPreference_Call) Run(run func(ctx context.Context, id int, notificationType string)) *MockUserRepository_CheckPreference_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(string))
	})
	return _c
}

func (_c *MockUserRepository_CheckPreference_Call) Return(b bool, err error) *MockUserRepository_CheckPreference_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockUserRepository_CheckPreference_Call) RunAndReturn(run func(ctx context.Context, id int, notificationType string) (bool, error)) *MockUserRepository_CheckPreference_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) DeleteUser(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockUserRepository_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *MockUserRepository_Expecter) DeleteUser(ctx interface{}, id interface{}) *MockUserRepository_DeleteUser_Call {
	return &MockUserRepository_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, id)}
}

func (_c *MockUserRepository_DeleteUser_Call) Run(run func(ctx context.Context, id int)) *MockUserRepository_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockUserRepository_DeleteUser_Call) Return(err error) *MockUserRepository_DeleteUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_DeleteUser_Call) RunAndReturn(run func(ctx context.Context, id int) error) *MockUserRepository_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllUsers provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetAllUsers(ctx context.Context) ([]models.User, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllUsers")
	}

	var r0 []models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]models.User, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []models.User); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetAllUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllUsers'
type MockUserRepository_GetAllUsers_Call struct {
	*mock.Call
}

// GetAllUsers is a helper method to define mock.On call
//   - ctx
func (_e *MockUserRepository_Expecter) GetAllUsers(ctx interface{}) *MockUserRepository_GetAllUsers_Call {
	return &MockUserRepository_GetAllUsers_Call{Call: _e.mock.On("GetAllUsers", ctx)}
}

func (_c *MockUserRepository_GetAllUsers_Call) Run(run func(ctx context.Context)) *MockUserRepository_GetAllUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockUserRepository_GetAllUsers_Call) Return(users []models.User, err error) *MockUserRepository_GetAllUsers_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockUserRepository_GetAllUsers_Call) RunAndReturn(run func(ctx context.Context) ([]models.User, error)) *MockUserRepository_GetAllUsers_Call {
	_c.Call.Return(run)
	return _c
}

// GetNotificationPreference provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetNotificationPreference(ctx context.Context, id int) (*models.NotificationPreference, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetNotificationPreference")
	}

	var r0 *models.NotificationPreference
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*models.NotificationPreference, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *models.NotificationPreference); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.NotificationPreference)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetNotificationPreference_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNotificationPreference'
type MockUserRepository_GetNotificationPreference_Call struct {
	*mock.Call
}

// GetNotificationPreference is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *MockUserRepository_Expecter) GetNotificationPreference(ctx interface{}, id interface{}) *MockUserRepository_GetNotificationPreference_Call {
	return &MockUserRepository_GetNotificationPreference_Call{Call: _e.mock.On("GetNotificationPreference", ctx, id)}
}

func (_c *MockUserRepository_GetNotificationPreference_Call) Run(run func(ctx context.Context, id int)) *MockUserRepository_GetNotificationPreference_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockUserRepository_GetNotificationPreference_Call) Return(notificationPreference *models.NotificationPreference, err error) *MockUserRepository_GetNotificationPreference_Call {
	_c.Call.Return(notificationPreference, err)
	return _c
}

func (_c *MockUserRepository_GetNotificationPreference_Call) RunAndReturn(run func(ctx context.Context, id int) (*models.NotificationPreference, error)) *MockUserRepository_GetNotificationPreference_Call {
	_c.Call.Return(run)
	return _c
}

// GetPasswordResetTokenInfo provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetPasswordResetTokenInfo(ctx context.Context, token string) (*models.PasswordResetData, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetPasswordResetTokenInfo")
	}

	var r0 *models.PasswordResetData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.PasswordResetData, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.PasswordResetData); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PasswordResetData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetPasswordResetTokenInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPasswordResetTokenInfo'
type MockUserRepository_GetPasswordResetTokenInfo_Call struct {
	*mock.Call
}

// GetPasswordResetTokenInfo is a helper method to define mock.On call
//   - ctx
//   - token
func (_e *MockUserRepository_Expecter) GetPasswordResetTokenInfo(ctx interface{}, token interface{}) *MockUserRepository_GetPasswordResetTokenInfo_Call {
	return &MockUserRepository_GetPasswordResetTokenInfo_Call{Call: _e.mock.On("GetPasswordResetTokenInfo", ctx, token)}
}

func (_c *MockUserRepository_GetPasswordResetTokenInfo_Call) Run(run func(ctx context.Context, token string)) *MockUserRepository_GetPasswordResetTokenInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRepository_GetPasswordResetTokenInfo_Call) Return(passwordResetData *models.PasswordResetData, err error) *MockUserRepository_GetPasswordResetTokenInfo_Call {
	_c.Call.Return(passwordResetData, err)
	return _c
}

func (_c *MockUserRepository_GetPasswordResetTokenInfo_Call) RunAndReturn(run func(ctx context.Context, token string) (*models.PasswordResetData, error)) *MockUserRepository_GetPasswordResetTokenInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetUser(ctx context.Context, id int) (*models.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*models.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *models.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockUserRepository_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *MockUserRepository_Expecter) GetUser(ctx interface{}, id interface{}) *MockUserRepository_GetUser_Call {
	return &MockUserRepository_GetUser_Call{Call: _e.mock.On("GetUser", ctx, id)}
}

func (_c *MockUserRepository_GetUser_Call) Run(run func(ctx context.Context, id int)) *MockUserRepository_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockUserRepository_GetUser_Call) Return(user *models.User, err error) *MockUserRepository_GetUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_GetUser_Call) RunAndReturn(run func(ctx context.Context, id int) (*models.User, error)) *MockUserRepository_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmail provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetUserByEmail(ctx context.Context, email string) (*models.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type MockUserRepository_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - ctx
//   - email
func (_e *MockUserRepository_Expecter) GetUserByEmail(ctx interface{}, email interface{}) *MockUserRepository_GetUserByEmail_Call {
	return &MockUserRepository_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", ctx, email)}
}

func (_c *MockUserRepository_GetUserByEmail_Call) Run(run func(ctx context.Context, email string)) *MockUserRepository_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRepository_GetUserByEmail_Call) Return(user *models.User, err error) *MockUserRepository_GetUserByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_GetUserByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*models.User, error)) *MockUserRepository_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserNotificationsToken provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetUserNotificationsToken(ctx context.Context, id int) (models.NotificationTokens, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserNotificationsToken")
	}

	var r0 models.NotificationTokens
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (models.NotificationTokens, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) models.NotificationTokens); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(models.NotificationTokens)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetUserNotificationsToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserNotificationsToken'
type MockUserRepository_GetUserNotificationsToken_Call struct {
	*mock.Call
}

// GetUserNotificationsToken is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *MockUserRepository_Expecter) GetUserNotificationsToken(ctx interface{}, id interface{}) *MockUserRepository_GetUserNotificationsToken_Call {
	return &MockUserRepository_GetUserNotificationsToken_Call{Call: _e.mock.On("GetUserNotificationsToken", ctx, id)}
}

func (_c *MockUserRepository_GetUserNotificationsToken_Call) Run(run func(ctx context.Context, id int)) *MockUserRepository_GetUserNotificationsToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockUserRepository_GetUserNotificationsToken_Call) Return(notificationTokens models.NotificationTokens, err error) *MockUserRepository_GetUserNotificationsToken_Call {
	_c.Call.Return(notificationTokens, err)
	return _c
}

func (_c *MockUserRepository_GetUserNotificationsToken_Call) RunAndReturn(run func(ctx context.Context, id int) (models.NotificationTokens, error)) *MockUserRepository_GetUserNotificationsToken_Call {
	_c.Call.Return(run)
	return _c
}

// ModifyPassword provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) ModifyPassword(ctx context.Context, id int, password string) error {
	ret := _mock.Called(ctx, id, password)

	if len(ret) == 0 {
		panic("no return value specified for ModifyPassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) error); ok {
		r0 = returnFunc(ctx, id, password)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_ModifyPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ModifyPassword'
type MockUserRepository_ModifyPassword_Call struct {
	*mock.Call
}

// ModifyPassword is a helper method to define mock.On call
//   - ctx
//   - id
//   - password
func (_e *MockUserRepository_Expecter) ModifyPassword(ctx interface{}, id interface{}, password interface{}) *MockUserRepository_ModifyPassword_Call {
	return &MockUserRepository_ModifyPassword_Call{Call: _e.mock.On("ModifyPassword", ctx, id, password)}
}

func (_c *MockUserRepository_ModifyPassword_Call) Run(run func(ctx context.Context, id int, password string)) *MockUserRepository_ModifyPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(string))
	})
	return _c
}

func (_c *MockUserRepository_ModifyPassword_Call) Return(err error) *MockUserRepository_ModifyPassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_ModifyPassword_Call) RunAndReturn(run func(ctx context.Context, id int, password string) error) *MockUserRepository_ModifyPassword_Call {
	_c.Call.Return(run)
	return _c
}

// ModifyUser provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) ModifyUser(ctx context.Context, user *models.User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for ModifyUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_ModifyUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ModifyUser'
type MockUserRepository_ModifyUser_Call struct {
	*mock.Call
}

// ModifyUser is a helper method to define mock.On call
//   - ctx
//   - user
func (_e *MockUserRepository_Expecter) ModifyUser(ctx interface{}, user interface{}) *MockUserRepository_ModifyUser_Call {
	return &MockUserRepository_ModifyUser_Call{Call: _e.mock.On("ModifyUser", ctx, user)}
}

func (_c *MockUserRepository_ModifyUser_Call) Run(run func(ctx context.Context, user *models.User)) *MockUserRepository_ModifyUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.User))
	})
	return _c
}

func (_c *MockUserRepository_ModifyUser_Call) Return(err error) *MockUserRepository_ModifyUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_ModifyUser_Call) RunAndReturn(run func(ctx context.Context, user *models.User) error) *MockUserRepository_ModifyUser_Call {
	_c.Call.Return(run)
	return _c
}

// SetNotificationPreference provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) SetNotificationPreference(ctx context.Context, id int, preference models.NotificationPreferenceRequest) error {
	ret := _mock.Called(ctx, id, preference)

	if len(ret) == 0 {
		panic("no return value specified for SetNotificationPreference")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, models.NotificationPreferenceRequest) error); ok {
		r0 = returnFunc(ctx, id, preference)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_SetNotificationPreference_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetNotificationPreference'
type MockUserRepository_SetNotificationPreference_Call struct {
	*mock.Call
}

// SetNotificationPreference is a helper method to define mock.On call
//   - ctx
//   - id
//   - preference
func (_e *MockUserRepository_Expecter) SetNotificationPreference(ctx interface{}, id interface{}, preference interface{}) *MockUserRepository_SetNotificationPreference_Call {
	return &MockUserRepository_SetNotificationPreference_Call{Call: _e.mock.On("SetNotificationPreference", ctx, id, preference)}
}

func (_c *MockUserRepository_SetNotificationPreference_Call) Run(run func(ctx context.Context, id int, preference models.NotificationPreferenceRequest)) *MockUserRepository_SetNotificationPreference_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(models.NotificationPreferenceRequest))
	})
	return _c
}

func (_c *MockUserRepository_SetNotificationPreference_Call) Return(err error) *MockUserRepository_SetNotificationPreference_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_SetNotificationPreference_Call) RunAndReturn(run func(ctx context.Context, id int, preference models.NotificationPreferenceRequest) error) *MockUserRepository_SetNotificationPreference_Call {
	_c.Call.Return(run)
	return _c
}

// SetPasswordTokenUsed provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) SetPasswordTokenUsed(ctx context.Context, token string) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for SetPasswordTokenUsed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_SetPasswordTokenUsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPasswordTokenUsed'
type MockUserRepository_SetPasswordTokenUsed_Call struct {
	*mock.Call
}

// SetPasswordTokenUsed is a helper method to define mock.On call
//   - ctx
//   - token
func (_e *MockUserRepository_Expecter) SetPasswordTokenUsed(ctx interface{}, token interface{}) *MockUserRepository_SetPasswordTokenUsed_Call {
	return &MockUserRepository_SetPasswordTokenUsed_Call{Call: _e.mock.On("SetPasswordTokenUsed", ctx, token)}
}

func (_c *MockUserRepository_SetPasswordTokenUsed_Call) Run(run func(ctx context.Context, token string)) *MockUserRepository_SetPasswordTokenUsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRepository_SetPasswordTokenUsed_Call) Return(err error) *MockUserRepository_SetPasswordTokenUsed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_SetPasswordTokenUsed_Call) RunAndReturn(run func(ctx context.Context, token string) error) *MockUserRepository_SetPasswordTokenUsed_Call {
	_c.Call.Return(run)
	return _c
}

// SetVerifiedTrue provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) SetVerifiedTrue(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for SetVerifiedTrue")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_SetVerifiedTrue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetVerifiedTrue'
type MockUserRepository_SetVerifiedTrue_Call struct {
	*mock.Call
}

// SetVerifiedTrue is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *MockUserRepository_Expecter) SetVerifiedTrue(ctx interface{}, id interface{}) *MockUserRepository_SetVerifiedTrue_Call {
	return &MockUserRepository_SetVerifiedTrue_Call{Call: _e.mock.On("SetVerifiedTrue", ctx, id)}
}

func (_c *MockUserRepository_SetVerifiedTrue_Call) Run(run func(ctx context.Context, id int)) *MockUserRepository_SetVerifiedTrue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockUserRepository_SetVerifiedTrue_Call) Return(err error) *MockUserRepository_SetVerifiedTrue_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_SetVerifiedTrue_Call) RunAndReturn(run func(ctx context.Context, id int) error) *MockUserRepository_SetVerifiedTrue_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVerificationRepository creates a new instance of MockVerificationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVerificationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVerificationRepository {
	mock := &MockVerificationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVerificationRepository is an autogenerated mock type for the VerificationRepository type
type MockVerificationRepository struct {
	mock.Mock
}

type MockVerificationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVerificationRepository) EXPECT() *MockVerificationRepository_Expecter {
	return &MockVerificationRepository_Expecter{mock: &_m.Mock}
}

// AddPendingVerification provides a mock function for the type MockVerificationRepository
func (_mock *MockVerificationRepository) AddPendingVerification(ctx context.Context, verification *models.UserVerification) (int, error) {
	ret := _mock.Called(ctx, verification)

	if len(ret) == 0 {
		panic("no return value specified for AddPendingVerification")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.UserVerification) (int, error)); ok {
		return returnFunc(ctx, verification)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.UserVerification) int); ok {
		r0 = returnFunc(ctx, verification)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.UserVerification) error); ok {
		r1 = returnFunc(ctx, verification)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVerificationRepository_AddPendingVerification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPendingVerification'
type MockVerificationRepository_AddPendingVerification_Call struct {
	*mock.Call
}

// AddPendingVerification is a helper method to define mock.On call
//   - ctx
//   - verification
func (_e *MockVerificationRepository_Expecter) AddPendingVerification(ctx interface{}, verification interface{}) *MockVerificationRepository_AddPendingVerification_Call {
	return &MockVerificationRepository_AddPendingVerification_Call{Call: _e.mock.On("AddPendingVerification", ctx, verification)}
}

func (_c *MockVerificationRepository_AddPendingVerification_Call) Run(run func(ctx context.Context, verification *models.UserVerification)) *MockVerificationRepository_AddPendingVerification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.UserVerification))
	})
	return _c
}

func (_c *MockVerificationRepository_AddPendingVerification_Call) Return(n int, err error) *MockVerificationRepository_AddPendingVerification_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockVerificationRepository_AddPendingVerification_Call) RunAndReturn(run func(ctx context.Context, verification *models.UserVerification) (int, error)) *MockVerificationRepository_AddPendingVerification_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByUserId provides a mock function for the type MockVerificationRepository
func (_mock *MockVerificationRepository) DeleteByUserId(ctx context.Context, userId int) error {
	ret := _mock.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByUserId")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, userId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVerificationRepository_DeleteByUserId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByUserId'
type MockVerificationRepository_DeleteByUserId_Call struct {
	*mock.Call
}

// DeleteByUserId is a helper method to define mock.On call
//   - ctx
//   - userId
func (_e *MockVerificationRepository_Expecter) DeleteByUserId(ctx interface{}, userId interface{}) *MockVerificationRepository_DeleteByUserId_Call {
	return &MockVerificationRepository_DeleteByUserId_Call{Call: _e.mock.On("DeleteByUserId", ctx, userId)}
}

func (_c *MockVerificationRepository_DeleteByUserId_Call) Run(run func(ctx context.Context, userId int)) *MockVerificationRepository_DeleteByUserId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockVerificationRepository_DeleteByUserId_Call) Return(err error) *MockVerificationRepository_DeleteByUserId_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVerificationRepository_DeleteByUserId_Call) RunAndReturn(run func(ctx context.Context, userId int) error) *MockVerificationRepository_DeleteByUserId_Call {
	_c.Call.Return(run)
	return _c
}

// GetVerificationByEmail provides a mock function for the type MockVerificationRepository
func (_mock *MockVerificationRepository) GetVerificationByEmail(ctx context.Context, email string) (*models.UserVerification, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetVerificationByEmail")
	}

	var r0 *models.UserVerification
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.UserVerification, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.UserVerification); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserVerification)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVerificationRepository_GetVerificationByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVerificationByEmail'
type MockVerificationRepository_GetVerificationByEmail_Call struct {
	*mock.Call
}

// GetVerificationByEmail is a helper method to define mock.On call
//   - ctx
//   - email
func (_e *MockVerificationRepository_Expecter) GetVerificationByEmail(ctx interface{}, email interface{}) *MockVerificationRepository_GetVerificationByEmail_Call {
	return &MockVerificationRepository_GetVerificationByEmail_Call{Call: _e.mock.On("GetVerificationByEmail", ctx, email)}
}

func (_c *MockVerificationRepository_GetVerificationByEmail_Call) Run(run func(ctx context.Context, email string)) *MockVerificationRepository_GetVerificationByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockVerificationRepository_GetVerificationByEmail_Call) Return(userVerification *models.UserVerification, err error) *MockVerificationRepository_GetVerificationByEmail_Call {
	_c.Call.Return(userVerification, err)
	return _c
}

func (_c *MockVerificationRepository_GetVerificationByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*models.UserVerification, error)) *MockVerificationRepository_GetVerificationByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetVerificationById provides a mock function for the type MockVerificationRepository
func (_mock *MockVerificationRepository) GetVerificationById(ctx context.Context, id int) (*models.UserVerification, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetVerificationById")
	}

	var r0 *models.UserVerification
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*models.UserVerification, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *models.UserVerification); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserVerification)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVerificationRepository_GetVerificationById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVerificationById'
type MockVerificationRepository_GetVerificationById_Call struct {
	*mock.Call
}

// GetVerificationById is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *MockVerificationRepository_Expecter) GetVerificationById(ctx interface{}, id interface{}) *MockVerificationRepository_GetVerificationById_Call {
	return &MockVerificationRepository_GetVerificationById_Call{Call: _e.mock.On("GetVerificationById", ctx, id)}
}

func (_c *MockVerificationRepository_GetVerificationById_Call) Run(run func(ctx context.Context, id int)) *MockVerificationRepository_GetVerificationById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockVerificationRepository_GetVerificationById_Call) Return(userVerification *models.UserVerification, err error) *MockVerificationRepository_GetVerificationById_Call {
	_c.Call.Return(userVerification, err)
	return _c
}

func (_c *MockVerificationRepository_GetVerificationById_Call) RunAndReturn(run func(ctx context.Context, id int) (*models.UserVerification, error)) *MockVerificationRepository_GetVerificationById_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePin provides a mock function for the type MockVerificationRepository
func (_mock *MockVerificationRepository) UpdatePin(ctx context.Context, userId int, pin string) error {
	ret := _mock.Called(ctx, userId, pin)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePin")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) error); ok {
		r0 = returnFunc(ctx, userId, pin)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVerificationRepository_UpdatePin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePin'
type MockVerificationRepository_UpdatePin_Call struct {
	*mock.Call
}

// UpdatePin is a helper method to define mock.On call
//   - ctx
//   - userId
//   - pin
func (_e *MockVerificationRepository_Expecter) UpdatePin(ctx interface{}, userId interface{}, pin interface{}) *MockVerificationRepository_UpdatePin_Call {
	return &MockVerificationRepository_UpdatePin_Call{Call: _e.mock.On("UpdatePin", ctx, userId, pin)}
}

func (_c *MockVerificationRepository_UpdatePin_Call) Run(run func(ctx context.Context, userId int, pin string)) *MockVerificationRepository_UpdatePin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(string))
	})
	return _c
}

func (_c *MockVerificationRepository_UpdatePin_Call) Return(err error) *MockVerificationRepository_UpdatePin_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVerificationRepository_UpdatePin_Call) RunAndReturn(run func(ctx context.Context, userId int, pin string) error) *MockVerificationRepository_UpdatePin_Call {
	_c.Call.Return(run)
	return _c
}
