name: CI/CD Pipeline

on:
  push:
    branches:
    - '**'
  pull_request:
    branches:
    - '**'
jobs:
  code-check:
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install dependencies
        run: go mod tidy

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: build compose
        run: docker compose up --build -d

      - name: Wait for API to become healthy
        run: |
            echo "Checking API health..."
            for i in {1..10}; do
              STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/health)
              if [ "$STATUS" -eq 200 ]; then
                echo "✅ API is healthy!"
                exit 0
              fi
              echo "Waiting for API... ($i/10)"
              sleep 2
            done
            echo "❌ API failed to start."
            docker compose logs
            exit 1

      - name: Run tests
        run: go test -v ./...

      - name: Stop Docker
        run: docker compose stop