name: CI/CD Pipeline

on:
  push:
    branches:
    - '**'
  pull_request:
    branches:
    - '**'
jobs:
  code-check:
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests with coverage
        run: go test ./internal/... -coverprofile=coverage.out

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Ingenieria-de-Software-2-Gupo-14/user-api
