name: CI/CD Pipeline

on:
  push:
    branches:
    - '**'
  pull_request:
    branches:
    - '**'
jobs:
  code-check:
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests with coverage
        run: go test ./internal/... -coverprofile=coverage.out

      - name: Show coverage summary
        run: go tool cover -func=coverage.out

      - name: Fail if coverage is below threshold
        run: |
          total=$(go tool cover -func=coverage.out | grep total: | awk '{print substr($3, 1, length($3)-1)}')
          threshold=75.0
          echo "Total coverage: $total%"
          awk -v t=$threshold -v c=$total 'BEGIN {exit (c < t) ? 1 : 0}'